### PR TITLE
Port to Python3

### PR DESCRIPTION
**Pull request by ronwellman**
I just noticed someone also put in a pull request for Python3 after I pushed my updates.  Putting in this PR merely for added emphasis.  Wonderful tool that I couldn't use on my Ubuntu 20.04 machine until I adapted it to Python3.  Again, wonderful tool.

### CODE REVIEW

**Comment by jameshilliard** [comment]
Have a few fixes here for [that](https://github.com/ach5948/jefferson/pull/1/files) other pull request, not sure if this needs them or not.

**Comment by ghost** [comment]
@ronwellman Tried your code, but I seem to be getting errors:
```
Traceback (most recent call last):
  File "/usr/local/bin/jefferson", line 12, in <module>
    from jefferson import jffs2_lzma, rtime
ImportError: cannot import name 'jffs2_lzma' from 'jefferson' (unknown location)

```

**Comment by sviehb** [comment]
Thank you for your work. I've included the changes from https://github.com/jameshilliard/jefferson/commit/981c13b7c9d90c6f84b54c3ccb397f2e4836bf98, looks fine 👍

**Comment by ronwellman** [comment]
Sorry I didn't get back earlier.  I was busy at work and haven't been able to focus on much else.  I'm glad you were able to sort out the issue.  Thanks for putting together this important project.

**Pull request merged**
